// <auto-generated />
using System;
using ClubId.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubId.Migrations
{
    [DbContext(typeof(LigabdContext))]
    [Migration("20260302213546_MigracionPostgresFinal")]
    partial class MigracionPostgresFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubId.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCategorias");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategorias"));

                    b.Property<bool>("EstadoCat")
                        .HasColumnType("boolean")
                        .HasColumnName("estadoCat");

                    b.Property<string>("NombreCat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombreCat");

                    b.HasKey("IdCategorias")
                        .HasName("PK_Categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idEquipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("celular");

                    b.Property<string>("Delegado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("delegado")
                        .HasDefaultValueSql("''");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("FotoEq")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fotoEq");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idCategoria");

                    b.Property<string>("NombreEq")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombreEq")
                        .HasDefaultValueSql("''");

                    b.HasKey("IdEquipo")
                        .HasName("PK_Equipos");

                    b.HasIndex(new[] { "IdCategoria" }, "idCategoria");

                    b.ToTable("equipos", null, t =>
                        {
                            t.HasComment("Equipos de la Liga, el cual tiene una foranea que me lleva a la categoria donde juega");
                        });
                });

            modelBuilder.Entity("ClubId.Models.Equipoxpartido", b =>
                {
                    b.Property<int>("IdExP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idExP");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExP"));

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer")
                        .HasColumnName("idEquipo");

                    b.Property<int>("IdEquipo2")
                        .HasColumnType("integer")
                        .HasColumnName("idEquipo2");

                    b.Property<int>("IdPartido")
                        .HasColumnType("integer")
                        .HasColumnName("idPartido");

                    b.Property<int?>("Resultado")
                        .HasColumnType("integer")
                        .HasColumnName("resultado");

                    b.Property<int?>("Resultado2")
                        .HasColumnType("integer")
                        .HasColumnName("resultado2");

                    b.HasKey("IdExP")
                        .HasName("PK_Equipoxpartidos");

                    b.HasIndex(new[] { "IdEquipo" }, "FK_equipoxpartido_equipos");

                    b.HasIndex(new[] { "IdEquipo2" }, "FK_equipoxpartido_equipos2");

                    b.HasIndex(new[] { "IdPartido" }, "FK_equipoxpartido_partidos");

                    b.ToTable("equipoxpartido", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Equipoxtorneo", b =>
                {
                    b.Property<int>("IdExT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idExT");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExT"));

                    b.Property<int?>("Empatados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empatados")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("Ganados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ganados")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("GolesContra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("golesContra")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("GolesFavor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("golesFavor")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("integer")
                        .HasColumnName("idTorneo");

                    b.Property<int>("Idequipo")
                        .HasColumnType("integer")
                        .HasColumnName("idequipo");

                    b.Property<int?>("Jugados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jugados")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("Perdidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("perdidos")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("puntos")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("IdExT")
                        .HasName("PK_Equipoxtorneos");

                    b.HasIndex(new[] { "IdTorneo" }, "FK_equipoxtorneo_torneos");

                    b.HasIndex(new[] { "Idequipo", "IdTorneo" }, "idequipo_idToreno")
                        .IsUnique();

                    b.ToTable("equipoxtorneo", null, t =>
                        {
                            t.HasComment("los equipos que jugan X torneo");
                        });
                });

            modelBuilder.Entity("ClubId.Models.Fecha", b =>
                {
                    b.Property<int>("IdFecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idFecha");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFecha"));

                    b.Property<DateOnly?>("Fechora")
                        .HasColumnType("date")
                        .HasColumnName("fechora");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("integer")
                        .HasColumnName("idTorneo");

                    b.Property<int>("NroFecha")
                        .HasColumnType("integer")
                        .HasColumnName("nroFecha");

                    b.HasKey("IdFecha")
                        .HasName("PK_Fechas");

                    b.HasIndex(new[] { "IdTorneo" }, "FK__torneos");

                    b.HasIndex(new[] { "NroFecha", "IdTorneo" }, "nroFecha_idTorneo")
                        .IsUnique();

                    b.ToTable("fechas", null, t =>
                        {
                            t.HasComment("son las fechas de los torneos, su tamaño esta dado por la cantidad de equipos que tenga el torneo\r\n");
                        });
                });

            modelBuilder.Entity("ClubId.Models.Jgrxequipo", b =>
                {
                    b.Property<int>("IdJxE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idJxE");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJxE"));

                    b.Property<DateTime>("FechaRecibo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechaRecibo");

                    b.Property<int>("IdCategorias")
                        .HasColumnType("integer")
                        .HasColumnName("idCategorias");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer")
                        .HasColumnName("idEquipo");

                    b.Property<int>("Idjugador")
                        .HasColumnType("integer")
                        .HasColumnName("idjugador");

                    b.HasKey("IdJxE")
                        .HasName("PK_Jgrxequipos");

                    b.HasIndex(new[] { "IdEquipo" }, "FK1_Equipos");

                    b.HasIndex(new[] { "Idjugador" }, "FK2_Jugadores");

                    b.HasIndex(new[] { "IdCategorias" }, "FK3_Categorias");

                    b.ToTable("jgrxequipo", null, t =>
                        {
                            t.HasComment("el jugador Y en el equipo X con FK de las talblas equipos y de jugadores");
                        });
                });

            modelBuilder.Entity("ClubId.Models.Jueqxsancion", b =>
                {
                    b.Property<int>("IdJexS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idJexS");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJexS"));

                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer")
                        .HasColumnName("idEquipo");

                    b.Property<int>("IdSanciones")
                        .HasColumnType("integer")
                        .HasColumnName("idSanciones");

                    b.Property<int>("Idjugador")
                        .HasColumnType("integer")
                        .HasColumnName("idjugador");

                    b.Property<string>("Informe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("informe");

                    b.Property<string>("Sancion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sancion");

                    b.HasKey("IdJexS")
                        .HasName("PK_Jueqxsancion");

                    b.HasIndex(new[] { "IdSanciones" }, "FK1_Sanciones");

                    b.HasIndex(new[] { "Idjugador" }, "FK2_Jugador");

                    b.HasIndex(new[] { "IdEquipo" }, "FK3_Equipo");

                    b.ToTable("jueqxsancion", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Jugadore", b =>
                {
                    b.Property<int>("Idjugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idjugador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idjugador"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dni")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date")
                        .HasColumnName("fechaNac");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int?>("NroCarnetOld")
                        .HasColumnType("integer")
                        .HasColumnName("nroCarnetOld");

                    b.HasKey("Idjugador")
                        .HasName("PK_Jugadores");

                    b.ToTable("jugadores", null, t =>
                        {
                            t.HasComment("datos del jugador");
                        });
                });

            modelBuilder.Entity("ClubId.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario")
                        .HasDefaultValueSql("''");

                    b.HasKey("Id")
                        .HasName("PK_Login");

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Partido", b =>
                {
                    b.Property<int>("IdPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idPartido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartido"));

                    b.Property<int?>("Cancha")
                        .HasColumnType("integer")
                        .HasColumnName("cancha");

                    b.Property<TimeOnly?>("Horario")
                        .HasColumnType("time")
                        .HasColumnName("horario");

                    b.Property<int>("IdFecha")
                        .HasColumnType("integer")
                        .HasColumnName("idFecha");

                    b.Property<int?>("NroPartido")
                        .HasColumnType("integer")
                        .HasColumnName("nroPartido");

                    b.HasKey("IdPartido")
                        .HasName("PK_Partidos");

                    b.HasIndex(new[] { "IdFecha", "NroPartido" }, "idFecha_nroPartido")
                        .IsUnique();

                    b.ToTable("partidos", null, t =>
                        {
                            t.HasComment("todos los partido de la fecha");
                        });
                });

            modelBuilder.Entity("ClubId.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id")
                        .HasName("PK_Players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Sancione", b =>
                {
                    b.Property<int>("IdSanciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idSanciones");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSanciones"));

                    b.Property<string>("Comunicado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCategorias")
                        .HasColumnType("integer")
                        .HasColumnName("idCategorias");

                    b.Property<int>("NroFecha")
                        .HasColumnType("integer");

                    b.HasKey("IdSanciones")
                        .HasName("PK_Sanciones");

                    b.HasIndex(new[] { "IdCategorias" }, "FK1_SCategorias");

                    b.ToTable("sanciones", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Torneo", b =>
                {
                    b.Property<int>("IdTorneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idTorneo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTorneo"));

                    b.Property<int?>("CantEquipos")
                        .HasColumnType("integer")
                        .HasColumnName("cantEquipos");

                    b.Property<int?>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idCategoria");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTorneo")
                        .HasName("PK_Torneos");

                    b.HasIndex(new[] { "IdCategoria" }, "FK_torneos_categorias");

                    b.ToTable("torneos", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("avatar");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nombre");

                    b.Property<string>("Planeta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("planeta");

                    b.HasKey("Id")
                        .HasName("PK_Usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ClubId.Models.Equipo", b =>
                {
                    b.HasOne("ClubId.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Equipos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK1_Categorias");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Equipoxpartido", b =>
                {
                    b.HasOne("ClubId.Models.Equipo", "IdEquipoNavigation")
                        .WithMany("EquipoxpartidoIdEquipoNavigations")
                        .HasForeignKey("IdEquipo")
                        .IsRequired()
                        .HasConstraintName("FK_equipoxpartido_equipos");

                    b.HasOne("ClubId.Models.Equipo", "IdEquipo2Navigation")
                        .WithMany("EquipoxpartidoIdEquipo2Navigations")
                        .HasForeignKey("IdEquipo2")
                        .IsRequired()
                        .HasConstraintName("FK_equipoxpartido_partidos_2");

                    b.HasOne("ClubId.Models.Partido", "IdPartidoNavigation")
                        .WithMany("Equipoxpartidos")
                        .HasForeignKey("IdPartido")
                        .IsRequired()
                        .HasConstraintName("FK_equipoxpartido_partidos");

                    b.Navigation("IdEquipo2Navigation");

                    b.Navigation("IdEquipoNavigation");

                    b.Navigation("IdPartidoNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Equipoxtorneo", b =>
                {
                    b.HasOne("ClubId.Models.Torneo", "IdTorneoNavigation")
                        .WithMany("Equipoxtorneos")
                        .HasForeignKey("IdTorneo")
                        .IsRequired()
                        .HasConstraintName("FK_equipoxtorneo_torneos");

                    b.HasOne("ClubId.Models.Equipo", "IdequipoNavigation")
                        .WithMany("Equipoxtorneos")
                        .HasForeignKey("Idequipo")
                        .IsRequired()
                        .HasConstraintName("FK_equipoxtorneo_equipos");

                    b.Navigation("IdTorneoNavigation");

                    b.Navigation("IdequipoNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Fecha", b =>
                {
                    b.HasOne("ClubId.Models.Torneo", "IdTorneoNavigation")
                        .WithMany("Fechas")
                        .HasForeignKey("IdTorneo")
                        .IsRequired()
                        .HasConstraintName("FK__torneos");

                    b.Navigation("IdTorneoNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Jgrxequipo", b =>
                {
                    b.HasOne("ClubId.Models.Categoria", "IdCategoriasNavigation")
                        .WithMany("Jgrxequipos")
                        .HasForeignKey("IdCategorias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK3_Categorias");

                    b.HasOne("ClubId.Models.Equipo", "IdEquipoNavigation")
                        .WithMany("Jgrxequipos")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK1_Equipos");

                    b.HasOne("ClubId.Models.Jugadore", "IdjugadorNavigation")
                        .WithMany("Jgrxequipos")
                        .HasForeignKey("Idjugador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK2_Jugadores");

                    b.Navigation("IdCategoriasNavigation");

                    b.Navigation("IdEquipoNavigation");

                    b.Navigation("IdjugadorNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Jueqxsancion", b =>
                {
                    b.HasOne("ClubId.Models.Equipo", "IdEquipoNavigation")
                        .WithMany("Jueqxsancions")
                        .HasForeignKey("IdEquipo")
                        .IsRequired()
                        .HasConstraintName("jueqxsancion_ibfk_3");

                    b.HasOne("ClubId.Models.Sancione", "IdSancionesNavigation")
                        .WithMany("Jueqxsancions")
                        .HasForeignKey("IdSanciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("jueqxsancion_ibfk_1");

                    b.HasOne("ClubId.Models.Jugadore", "IdjugadorNavigation")
                        .WithMany("Jueqxsancions")
                        .HasForeignKey("Idjugador")
                        .IsRequired()
                        .HasConstraintName("jueqxsancion_ibfk_2");

                    b.Navigation("IdEquipoNavigation");

                    b.Navigation("IdSancionesNavigation");

                    b.Navigation("IdjugadorNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Partido", b =>
                {
                    b.HasOne("ClubId.Models.Fecha", "IdFechaNavigation")
                        .WithMany("Partidos")
                        .HasForeignKey("IdFecha")
                        .IsRequired()
                        .HasConstraintName("FK_partidos_fechas");

                    b.Navigation("IdFechaNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Sancione", b =>
                {
                    b.HasOne("ClubId.Models.Categoria", "IdCategoriasNavigation")
                        .WithMany("Sanciones")
                        .HasForeignKey("IdCategorias")
                        .IsRequired()
                        .HasConstraintName("FK1_SCategorias");

                    b.Navigation("IdCategoriasNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Torneo", b =>
                {
                    b.HasOne("ClubId.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Torneos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_torneos_categorias");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("ClubId.Models.Categoria", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Jgrxequipos");

                    b.Navigation("Sanciones");

                    b.Navigation("Torneos");
                });

            modelBuilder.Entity("ClubId.Models.Equipo", b =>
                {
                    b.Navigation("EquipoxpartidoIdEquipo2Navigations");

                    b.Navigation("EquipoxpartidoIdEquipoNavigations");

                    b.Navigation("Equipoxtorneos");

                    b.Navigation("Jgrxequipos");

                    b.Navigation("Jueqxsancions");
                });

            modelBuilder.Entity("ClubId.Models.Fecha", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("ClubId.Models.Jugadore", b =>
                {
                    b.Navigation("Jgrxequipos");

                    b.Navigation("Jueqxsancions");
                });

            modelBuilder.Entity("ClubId.Models.Partido", b =>
                {
                    b.Navigation("Equipoxpartidos");
                });

            modelBuilder.Entity("ClubId.Models.Sancione", b =>
                {
                    b.Navigation("Jueqxsancions");
                });

            modelBuilder.Entity("ClubId.Models.Torneo", b =>
                {
                    b.Navigation("Equipoxtorneos");

                    b.Navigation("Fechas");
                });
#pragma warning restore 612, 618
        }
    }
}
